#!/usr/bin/env python3
"""
Export the generated conversations into a HuggingFace-ready dataset.

Why this exists
---------------
The raw files under data/ are JSON *lists* with a nested `conversation` field whose
turns have inconsistent keys (tutor turns carry an `execution` sub-object, student
turns don't). That loads fine with `json.load`, but HuggingFace / Arrow infers a
single schema per column, so the inconsistent nested struct is fragile.

This script normalizes everything into a flat, self-consistent schema and writes:
  - dataset/train.jsonl        (streaming-friendly, git-diffable)
  - dataset/train.parquet      (columnar, what HF prefers for `load_dataset`)
  - dataset/README.md          (dataset card with YAML metadata)

Every conversation turn is normalized to the SAME keys (execution fields are null
for student turns) so the schema is stable across all 2,495 rows.

Usage:
    python export_huggingface.py                      # golden strategy1 dataset
    python export_huggingface.py --source data/strategy2_04_02_2026
"""
import argparse
import glob
import json
import os
from pathlib import Path

GOLDEN = "data/strategy1_11_02_2026-Golden"


def normalize_turn(msg: dict) -> dict:
    """Flatten a conversation turn to a stable schema (execution fields nullable)."""
    exe = msg.get("execution") or {}
    return {
        "role": msg.get("role", ""),
        "content": msg.get("content", ""),
        "turn": msg.get("turn"),
        "tests_passed": exe.get("tests_passed"),   # None for student turns
        "total_tests": exe.get("total_tests"),
        "success": exe.get("success"),
        "error_type": exe.get("error_type"),
        "message": exe.get("message"),
    }


def normalize_record(conv: dict) -> dict:
    """One conversation -> one flat, HF-friendly row."""
    return {
        "id": str(conv.get("id", "")),
        "task_id": conv.get("task_id"),
        # Strategy 1 uses `personality`; Strategy 2 uses `knowledge_level`.
        "personality": conv.get("personality"),
        "knowledge_level": conv.get("knowledge_level"),
        "strategy": conv.get("strategy"),
        "model": conv.get("model"),
        "problem_text": conv.get("problem_text", ""),
        "test_cases": conv.get("test_cases", []) or [],
        "conversation": [normalize_turn(m) for m in conv.get("conversation", [])],
        "solved": bool(conv.get("solved", False)),
        "tests_passed": conv.get("tests_passed"),
        "total_tests": conv.get("total_tests"),
        "turns": conv.get("turns"),
        "quality_bucket": conv.get("quality_bucket", "unknown"),
        "timestamp": str(conv.get("timestamp", "")),
    }


def load_source(source: str) -> list:
    rows = []
    for jf in sorted(glob.glob(os.path.join(source, "*_conversations.json"))):
        with open(jf) as f:
            for conv in json.load(f):
                rows.append(normalize_record(conv))
    return rows


def write_dataset_card(out_dir: Path, rows: list) -> None:
    from collections import Counter
    q = Counter(r["quality_bucket"] for r in rows)
    p = Counter(r["personality"] for r in rows if r["personality"])
    total = len(rows)
    trainable = q.get("gold", 0) + q.get("silver", 0)
    persona_lines = "\n".join(f"- **{k}**: {v}" for k, v in sorted(p.items()))

    card = f"""---
license: mit
task_categories:
  - text-generation
language:
  - en
tags:
  - code
  - synthetic
  - tutoring
  - conversational
  - debugging
pretty_name: Synthetic Coding Tutor Conversations
size_categories:
  - 1K<n<10K
configs:
  - config_name: default
    data_files:
      - split: train
        path: train.parquet
---

# Synthetic Coding Tutor Conversations

Multi-turn student–tutor debugging conversations generated by a LangGraph pipeline of
autonomous LLM agents. Each candidate solution is executed against real pytest test
cases, and every finished conversation is graded 0–10 by an LLM judge on persona
fidelity, tutor responsiveness, and dialog flow.

## Summary

- **Total conversations:** {total}
- **Training-ready (gold + silver):** {trainable}
- **Quality buckets:** gold={q.get('gold',0)}, silver={q.get('silver',0)}, bronze={q.get('bronze',0)}

### Conversations per personality
{persona_lines}

## Schema

Each row is one conversation:

| field | type | notes |
|-------|------|-------|
| `id` | string | unique conversation id |
| `task_id` | int | source problem id |
| `personality` | string | student persona (Strategy 1) |
| `knowledge_level` | string | student level (Strategy 2; null otherwise) |
| `problem_text` | string | the coding problem |
| `test_cases` | list[string] | pytest assertions used for validation |
| `conversation` | list[struct] | turns: `role, content, turn, tests_passed, total_tests, success, error_type, message` |
| `solved` | bool | did the final code pass all tests |
| `tests_passed` / `total_tests` | int | final execution result |
| `turns` | int | number of turns |
| `quality_bucket` | string | `gold` / `silver` / `bronze` |

Execution fields inside `conversation` turns are null for student turns (only tutor
turns are executed).

## Load

```python
from datasets import load_dataset
ds = load_dataset("<your-username>/synthetic-coding-tutor")["train"]

# Filter to training-ready conversations
train = ds.filter(lambda r: r["quality_bucket"] in ("gold", "silver"))
```

## Generation process

See the full pipeline and metrics: https://harshitbudhiraja.github.io/data_curation/
"""
    (out_dir / "README.md").write_text(card)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--source", default=GOLDEN, help="folder with *_conversations.json")
    ap.add_argument("--out", default="dataset", help="output directory")
    args = ap.parse_args()

    rows = load_source(args.source)
    if not rows:
        raise SystemExit(f"No *_conversations.json found in {args.source}")

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    # 1) JSONL — git-diffable, streaming-friendly
    with open(out_dir / "train.jsonl", "w") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")

    # 2) Parquet — what HuggingFace serves for load_dataset()
    try:
        from datasets import Dataset
        Dataset.from_list(rows).to_parquet(str(out_dir / "train.parquet"))
        parquet_ok = True
    except Exception as e:  # pragma: no cover
        parquet_ok = False
        print(f"[warn] parquet export skipped: {e}")

    # 3) Dataset card
    write_dataset_card(out_dir, rows)

    print(f"Exported {len(rows)} conversations -> {out_dir}/")
    print(f"  - train.jsonl")
    if parquet_ok:
        print(f"  - train.parquet")
    print(f"  - README.md (dataset card)")
    print("\nPush to the Hub with:")
    print("  huggingface-cli login")
    print(f"  huggingface-cli upload <username>/synthetic-coding-tutor {out_dir} . --repo-type dataset")


if __name__ == "__main__":
    main()
