"""Node wrapper functions for LangGraph - adapted for data_curation."""
import sys
import os
import re
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from langchain_core.messages import AIMessage, HumanMessage
from simulation.agents import StudentAgent, TutorAgent
from simulation.graph.state import AgentState
from run_python import run_python_code


def extract_function_name(test_cases: list) -> str:
    """Extract function name from test cases."""
    if not test_cases:
        return None
    match = re.search(r'assert\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\(', test_cases[0])
    if match:
        return match.group(1)
    return None


def student_node(state: AgentState) -> dict:
    """Student agent node - generates questions/responses.
    
    Args:
        state: Current graph state
    
    Returns:
        Updated state with student's message
    """
    agent = StudentAgent(
        personality_prompt=state["personality_prompt"],
        personality_name=state.get("personality", "CONFUSED_STUDENT")
    )
    
    function_name = extract_function_name(state["test_cases"])
    
    # Get execution result with total_tests added
    execution_result = state.get("execution_result")
    if execution_result:
        execution_result["total_tests"] = len(state["test_cases"])
    
    # Generate student response
    # Always pass the problem text to keep student focused
    response = agent.generate_response(
        conversation_history=state["messages"],
        problem=state["problem_text"],
        function_name=function_name,
        execution_result=execution_result
    )
    
    # Create message
    message = HumanMessage(content=response, name="student")
    
    # Print for user visibility
    print(f"\n👩‍🎓 STUDENT: {response[:150]}..." if len(response) > 150 else f"\n👩‍🎓 STUDENT: {response}")
    
    # Update state
    return {
        "messages": [message],
        "turn_count": state["turn_count"] + 1
    }


def tutor_node(state: AgentState) -> dict:
    """Tutor agent node - provides code solution.
    
    Args:
        state: Current graph state
    
    Returns:
        Updated state with tutor's code
    """
    agent = TutorAgent()
    
    function_name = extract_function_name(state["test_cases"])
    
    # Generate tutor response (should be pure code)
    response = agent.generate_response(
        conversation_history=state["messages"],
        problem=state["problem_text"],
        function_name=function_name,
        test_cases=state["test_cases"],
        turn_count=state["turn_count"],
        execution_result=state.get("execution_result")
    )
    
    # Create message
    message = AIMessage(content=response, name="tutor")
    
    # Print for user visibility (show first few lines of code)
    code_preview = response.split('\n')[:3]
    print(f"\n👨‍🏫 TUTOR CODE:\n" + '\n'.join(code_preview) + ("\n..." if len(response.split('\n')) > 3 else ""))
    
    # Update state
    return {
        "messages": [message],
        "turn_count": state["turn_count"] + 1
    }


def execution_node(state: AgentState) -> dict:
    """Executes the code generated by the tutor.
    
    Args:
        state: Current graph state
    
    Returns:
        Updated state with execution results
    """
    # Get the last message (should be tutor's code)
    last_message = state["messages"][-1]
    code_content = last_message.content if hasattr(last_message, 'content') else last_message['content']
    
    # Execute code with tests
    result = run_python_code(code_content, state["test_cases"])
    
    # Update solved status
    solved = result.get('success', False)
    tests_passed = result.get('tests_passed', 0)
    total_tests = len(state["test_cases"])
    
    # Add total_tests to result for student feedback
    result["total_tests"] = total_tests
    
    # Create execution record for this turn
    execution_record = {
        "turn": state["turn_count"],
        "tests_passed": tests_passed,
        "total_tests": total_tests,
        "success": solved,
        "error_type": result.get('error_type'),
        "message": result.get('message', '')
    }
    
    # Add to execution history
    execution_history = list(state.get("execution_history", []))
    execution_history.append(execution_record)
    
    # Print execution result with test progress
    if solved:
        print(f"\n✅ EXECUTION: All tests passed! ({tests_passed}/{total_tests})")
    else:
        print(f"\n❌ EXECUTION: Tests failed ({tests_passed}/{total_tests} passed) - {result.get('message', 'error')}")
    
    return {
        "execution_result": result,
        "solved": solved,
        "execution_history": execution_history
    }
